/**
 * @file ReviewResponse.h
 * @brief Definition of the ReviewResponse data structure.
 * @details This file defines the data object used to capture the results of an
 * AI code review request, including status, content, and raw debugging data.
 */

#ifndef _REVIEWRESPONSE_H
#define _REVIEWRESPONSE_H

#include <string>

/**
 * @struct ReviewResponse
 * @brief Represents the response received from a code review request.
 *
 * This structure acts as a Data Transfer Object (DTO) that holds the
 * outcome of the interaction with the AI service, separating the
 * parsed content from the raw protocol data.
 */
struct ReviewResponse {
    /**
     * @brief Indicates the success or failure of the review operation.
     *
     * True if the HTTP request was successful and the response was parsed correctly;
     * false otherwise.
     */
    bool success;

    /**
     * @brief The extracted review content.
     *
     * This string contains the actual markdown or text response generated by the AI
     * (the specific "response" field extracted from the JSON).
     */
    std::string content;

    /**
     * @brief The raw JSON string received from the server.
     *
     * Preserved for logging, debugging, or auditing purposes.
     */
    std::string rawJson;

    /**
     * @brief Description of the error, if any occurred.
     *
     * Populated only if `success` is false. This may contain HTTP error codes
     * or parsing exception messages.
     */
    std::string errorMessage;
};

#endif // _REVIEWRESPONSE_H